---
- name: Jenkins configuration file transfer.
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.owner }}'
    mode: '{{ item.mode }}'
  loop: '{{ jenkins_conf }}'
  when: item.create | default(true) | bool
  notify:
    - Restart Jenkins service.
