---
- name: Add the group jenkins.
  group:
    name: '{{ jenkins_arg.user }}'

- name: Add the user jenkins.
  user:
    name: '{{ jenkins_arg.user }}'
    comment: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    home: '{{ jenkins_path }}/jenkins'

- name: Creating Jenkins working folder.
  file:
    dest: '{{ jenkins_path }}/jenkins/{{ item }}'
    state: 'directory'
    owner: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    mode: '0750'
  loop:
    - 'conf'
    - 'bin'
    - 'libs'
    - 'logs'
    - 'tmp'

- name: Download Jenkins Web Application Resource file.
  get_url:
    url: '{{ jenkins_soft_url }}/war-stable/{{ jenkins_version }}/jenkins.war'
    dest: '{{ jenkins_path }}/jenkins/libs/jenkins.war'
    owner: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    mode: '640'
    validate_certs: 'no'
    timeout: '60'
  register: jenkins_upgrade
  until: jenkins_upgrade is succeeded
  retries: 5
  delay: 2

- name: Install Jenkins support binary package.
  copy:
    src: '{{ item }}'
    dest: '{{ jenkins_path }}/jenkins/bin/'
    owner: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    mode: '750'
  loop: '{{ jenkins_support_binary }}'

- name: Install Jenkins support library package.
  copy:
    src: '{{ item }}'
    dest: '{{ jenkins_path }}/jenkins/libs/'
    owner: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    mode: '640'
  loop: '{{ jenkins_support_jars }}'
