---
- name: Add the group jenkins.
  group:
    name: '{{ jenkins_arg.user }}'

- name: Add the user jenkins.
  user:
    name: '{{ jenkins_arg.user }}'
    comment: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    home: '{{ jenkins_path }}/jenkins'

- name: Creating Jenkins working folder.
  file:
    dest: '{{ jenkins_path }}/jenkins/{{ item.dest }}'
    state: 'directory'
    owner: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    mode: '0750'
  loop: '{{ jenkins_folder }}'
  when: item.create | default(true) | bool

- name: Download Jenkins Web Application Resource file.
  get_url:
    url: '{{ jenkins_soft_url }}/war-stable/{{ jenkins_version }}/jenkins.war'
    dest: '{{ jenkins_path }}/jenkins/libs/jenkins.war'
    owner: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    mode: '640'
    validate_certs: 'no'
    timeout: '60'
  register: jenkins_upgrade
  until: jenkins_upgrade is succeeded
  retries: 5
  delay: 2
  when: jenkins_nodes[0] in ansible_default_ipv4.address
  notify: Restart Jenkins service.

- name: Install Jenkins support binary package.
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ jenkins_arg.user }}'
    group: '{{ jenkins_arg.user }}'
    mode: '750'
  loop: '{{ jenkins_script }}'
  notify: Restart Jenkins service.
