---
- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Checking for Jenkins master status.
  uri:
    url: 'https://{{ ansible_default_ipv4.address }}:{{ jenkins_port.https }}/login'
    method: 'HEAD'
    validate_certs: 'no'
    status_code: '-1,200'
    headers:
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  when: jenkins_nodes[0] in ansible_default_ipv4.address
  register: jenkins_master_status

- name: Include installation tasks.
  include: 'install.yml'

- name: Include configuration tasks.
  include: 'configureation.yml'

- name: Include certificate tasks.
  include: 'certificates.yml'
  when: jenkins_nodes[0] in ansible_default_ipv4.address

- name: Flush handlers.
  meta: flush_handlers

- name: Check if Jenkins performed the action check updates successfully.
  stat:
    path: '{{ jenkins_path }}/jenkins/updates/hudson.tasks.Maven.MavenInstaller'
  register: jenkins_update_result
  until: jenkins_update_result.stat.exists
  retries: 30
  delay: 30
  when: jenkins_nodes[0] in ansible_default_ipv4.address

- name: Include plugins update task.
  include: 'plugin.yml'
  when: jenkins_nodes[0] in ansible_default_ipv4.address

- name: Flush handlers.
  meta: flush_handlers

- name: Remove Jenkins init groovy after startup.
  file:
    path: '{{ jenkins_path }}/jenkins/init.groovy.d/{{ item }}.groovy'
    state: 'absent'
  loop: '{{ jenkins_groovy }}'
  when:
    - jenkins_nodes[0] in ansible_default_ipv4.address
    - jenkins_master_status.status != 200

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Include Jenkins agent task.
  include: 'agent.yml'
  when: jenkins_nodes[0] not in ansible_default_ipv4.address
